export enum ACCOUNT_SERVICE_MESSAGE_PATTERN {
  SEND_VERIFICATION_EMAIL = "account-service.send-verification-email",
  SEND_PASSWORD_RESET_EMAIL = "account-service.send-password-reset-email",
  VERIFY_TOKEN = "account-service.verify-token",
  REGISTER = "account-service.register",
  LOGIN = "account-service.login",
  RESET_PASSWORD = "account-service.reset-password",
  WHOAMI = "account-service.whoami",
  LOGOUT = "account-service.logout",
  FIND_USER_BY_EMAIL = "account-service.find-user-by-email",
  REFRESH_TOKENS = "account-service.refresh-tokens",
  HEALTHCHECK = "account-service.healthcheck",
  UPLOAD_IMAGE = "account-service.upload-image",
  REMOVE_IMAGE = "account-service.remove-image",
  GET_SITTER_PROFILE = "account-service.get-sitter-profile",
  GET_CLIENT_PROFILE = "account-service.get-client-profile",
  UPDATE_USER_PROFILE = "account-service.update-user-profile",
  GET_RECOMMENDED_PROFILES = "account-service.get-recommended-profiles",
  GET_SITTER_PROFILE_BY_ID = "account-service.get-sitter-profile-by-id",
  GET_CLIENT_PROFILE_BY_ID = "account-service.get-client-profile-by-id",
  GET_FILTERED_PROFILES = "account-service.get-filtered-profiles",
}
